export interface GameItem {
  prompt: string;
  answer: string;
  hint?: string;
}

export const EQUATIONS_LIST: GameItem[] = [
  { prompt: "5 + 2 =", answer: "7" },
  { prompt: "6 + 3 =", answer: "9" },
  { prompt: "7 + 4 =", answer: "11" },
  { prompt: "8 + 5 =", answer: "13" },
  { prompt: "9 + 6 =", answer: "15" },
  { prompt: "10 + 7 =", answer: "17" },
  { prompt: "11 + 8 =", answer: "19" },
  { prompt: "12 + 9 =", answer: "21" },
  { prompt: "13 + 10 =", answer: "23" },
  { prompt: "14 + 11 =", answer: "25" },
  { prompt: "15 + 12 =", answer: "27" },
  { prompt: "16 + 13 =", answer: "29" },
  { prompt: "17 + 14 =", answer: "31" },
  { prompt: "18 + 15 =", answer: "33" },
  { prompt: "19 + 16 =", answer: "35" },
  { prompt: "15 - 2 =", answer: "13" },
  { prompt: "16 - 3 =", answer: "13" },
  { prompt: "17 - 4 =", answer: "13" },
  { prompt: "18 - 5 =", answer: "13" },
  { prompt: "19 - 6 =", answer: "13" },
  { prompt: "20 - 7 =", answer: "13" },
  { prompt: "21 - 8 =", answer: "13" },
  { prompt: "22 - 9 =", answer: "13" },
  { prompt: "23 - 10 =", answer: "13" },
  { prompt: "24 - 11 =", answer: "13" },
  { prompt: "25 - 12 =", answer: "13" },
  { prompt: "26 - 13 =", answer: "13" },
  { prompt: "27 - 14 =", answer: "13" },
  { prompt: "28 - 15 =", answer: "13" },
  { prompt: "29 - 16 =", answer: "13" },
  { prompt: "2 * 3 =", answer: "6" },
  { prompt: "3 * 4 =", answer: "12" },
  { prompt: "4 * 5 =", answer: "20" },
  { prompt: "5 * 6 =", answer: "30" },
  { prompt: "6 * 7 =", answer: "42" },
  { prompt: "7 * 8 =", answer: "56" },
  { prompt: "8 * 9 =", answer: "72" },
  { prompt: "9 * 10 =", answer: "90" },
  { prompt: "10 * 11 =", answer: "110" },
  { prompt: "11 * 12 =", answer: "132" },
  { prompt: "12 * 13 =", answer: "156" },
  { prompt: "13 * 14 =", answer: "182" },
  { prompt: "14 * 15 =", answer: "210" },
  { prompt: "15 * 16 =", answer: "240" },
  { prompt: "16 * 17 =", answer: "272" },
  { prompt: "8 / 2 =", answer: "4" },
  { prompt: "15 / 3 =", answer: "5" },
  { prompt: "24 / 4 =", answer: "6" },
  { prompt: "35 / 5 =", answer: "7" },
  { prompt: "48 / 6 =", answer: "8" },
  { prompt: "63 / 7 =", answer: "9" },
  { prompt: "80 / 8 =", answer: "10" },
  { prompt: "99 / 9 =", answer: "11" },
  { prompt: "120 / 10 =", answer: "12" },
  { prompt: "143 / 11 =", answer: "13" },
  { prompt: "5 + 2 =", answer: "7" },
  { prompt: "6 + 3 =", answer: "9" },
  { prompt: "7 + 4 =", answer: "11" },
  { prompt: "8 + 5 =", answer: "13" },
  { prompt: "9 + 6 =", answer: "15" },
  { prompt: "10 + 7 =", answer: "17" },
  { prompt: "11 + 8 =", answer: "19" },
  { prompt: "12 + 9 =", answer: "21" },
  { prompt: "13 + 10 =", answer: "23" },
  { prompt: "14 + 11 =", answer: "25" },
  { prompt: "15 + 12 =", answer: "27" },
  { prompt: "16 + 13 =", answer: "29" },
  { prompt: "17 + 14 =", answer: "31" },
  { prompt: "18 + 15 =", answer: "33" },
  { prompt: "19 + 16 =", answer: "35" },
  { prompt: "20 + 17 =", answer: "37" },
  { prompt: "21 + 18 =", answer: "39" },
  { prompt: "22 + 19 =", answer: "41" },
  { prompt: "23 + 20 =", answer: "43" },
  { prompt: "24 + 21 =", answer: "45" },
  { prompt: "25 + 22 =", answer: "47" },
  { prompt: "26 + 23 =", answer: "49" },
  { prompt: "27 + 24 =", answer: "51" },
  { prompt: "28 + 25 =", answer: "53" },
  { prompt: "29 + 26 =", answer: "55" },
  { prompt: "30 + 2 =", answer: "32" },
  { prompt: "31 + 3 =", answer: "34" },
  { prompt: "32 + 4 =", answer: "36" },
  { prompt: "33 + 5 =", answer: "38" },
  { prompt: "34 + 6 =", answer: "40" },
  { prompt: "35 + 7 =", answer: "42" },
  { prompt: "36 + 8 =", answer: "44" },
  { prompt: "37 + 9 =", answer: "46" },
  { prompt: "38 + 10 =", answer: "48" },
  { prompt: "39 + 11 =", answer: "50" },
  { prompt: "40 + 12 =", answer: "52" },
  { prompt: "41 + 13 =", answer: "54" },
  { prompt: "42 + 14 =", answer: "56" },
  { prompt: "43 + 15 =", answer: "58" },
  { prompt: "44 + 16 =", answer: "60" },
  { prompt: "45 + 17 =", answer: "62" },
  { prompt: "46 + 18 =", answer: "64" },
  { prompt: "47 + 19 =", answer: "66" },
  { prompt: "48 + 20 =", answer: "68" },
  { prompt: "49 + 21 =", answer: "70" },
  { prompt: "50 + 22 =", answer: "72" },
  { prompt: "51 + 23 =", answer: "74" },
  { prompt: "52 + 24 =", answer: "76" },
  { prompt: "53 + 25 =", answer: "78" },
  { prompt: "54 + 26 =", answer: "80" },
  { prompt: "55 + 2 =", answer: "57" },
  { prompt: "56 + 3 =", answer: "59" },
  { prompt: "57 + 4 =", answer: "61" },
  { prompt: "58 + 5 =", answer: "63" },
  { prompt: "59 + 6 =", answer: "65" },
  { prompt: "60 + 7 =", answer: "67" },
  { prompt: "61 + 8 =", answer: "69" },
  { prompt: "62 + 9 =", answer: "71" },
  { prompt: "63 + 10 =", answer: "73" },
  { prompt: "64 + 11 =", answer: "75" },
  { prompt: "65 + 12 =", answer: "77" },
  { prompt: "66 + 13 =", answer: "79" },
  { prompt: "67 + 14 =", answer: "81" },
  { prompt: "68 + 15 =", answer: "83" },
  { prompt: "69 + 16 =", answer: "85" },
  { prompt: "70 + 17 =", answer: "87" },
  { prompt: "71 + 18 =", answer: "89" },
  { prompt: "72 + 19 =", answer: "91" },
  { prompt: "73 + 20 =", answer: "93" },
  { prompt: "74 + 21 =", answer: "95" },
  { prompt: "75 + 22 =", answer: "97" },
  { prompt: "76 + 23 =", answer: "99" },
  { prompt: "77 + 24 =", answer: "101" },
  { prompt: "78 + 25 =", answer: "103" },
  { prompt: "79 + 26 =", answer: "105" },

  { prompt: "30 - 1 =", answer: "29" },
  { prompt: "31 - 2 =", answer: "29" },
  { prompt: "32 - 3 =", answer: "29" },
  { prompt: "33 - 4 =", answer: "29" },
  { prompt: "34 - 5 =", answer: "29" },
  { prompt: "35 - 6 =", answer: "29" },
  { prompt: "36 - 7 =", answer: "29" },
  { prompt: "37 - 8 =", answer: "29" },
  { prompt: "38 - 9 =", answer: "29" },
  { prompt: "39 - 10 =", answer: "29" },
  { prompt: "40 - 11 =", answer: "29" },
  { prompt: "41 - 12 =", answer: "29" },
  { prompt: "42 - 13 =", answer: "29" },
  { prompt: "43 - 14 =", answer: "29" },
  { prompt: "44 - 15 =", answer: "29" },
  { prompt: "45 - 16 =", answer: "29" },
  { prompt: "46 - 17 =", answer: "29" },
  { prompt: "47 - 18 =", answer: "29" },
  { prompt: "48 - 19 =", answer: "29" },
  { prompt: "49 - 20 =", answer: "29" },
  { prompt: "50 - 1 =", answer: "49" },
  { prompt: "51 - 2 =", answer: "49" },
  { prompt: "52 - 3 =", answer: "49" },
  { prompt: "53 - 4 =", answer: "49" },
  { prompt: "54 - 5 =", answer: "49" },
  { prompt: "55 - 6 =", answer: "49" },
  { prompt: "56 - 7 =", answer: "49" },
  { prompt: "57 - 8 =", answer: "49" },
  { prompt: "58 - 9 =", answer: "49" },
  { prompt: "59 - 10 =", answer: "49" },
  { prompt: "60 - 11 =", answer: "49" },
  { prompt: "61 - 12 =", answer: "49" },
  { prompt: "62 - 13 =", answer: "49" },
  { prompt: "63 - 14 =", answer: "49" },
  { prompt: "64 - 15 =", answer: "49" },
  { prompt: "65 - 16 =", answer: "49" },
  { prompt: "66 - 17 =", answer: "49" },
  { prompt: "67 - 18 =", answer: "49" },
  { prompt: "68 - 19 =", answer: "49" },
  { prompt: "69 - 20 =", answer: "49" },
  { prompt: "70 - 1 =", answer: "69" },
  { prompt: "71 - 2 =", answer: "69" },
  { prompt: "72 - 3 =", answer: "69" },
  { prompt: "73 - 4 =", answer: "69" },
  { prompt: "74 - 5 =", answer: "69" },
  { prompt: "75 - 6 =", answer: "69" },
  { prompt: "76 - 7 =", answer: "69" },
  { prompt: "77 - 8 =", answer: "69" },
  { prompt: "78 - 9 =", answer: "69" },
  { prompt: "79 - 10 =", answer: "69" },
  { prompt: "80 - 11 =", answer: "69" },
  { prompt: "81 - 12 =", answer: "69" },
  { prompt: "82 - 13 =", answer: "69" },
  { prompt: "83 - 14 =", answer: "69" },
  { prompt: "84 - 15 =", answer: "69" },
  { prompt: "85 - 16 =", answer: "69" },
  { prompt: "86 - 17 =", answer: "69" },
  { prompt: "87 - 18 =", answer: "69" },
  { prompt: "88 - 19 =", answer: "69" },
  { prompt: "89 - 20 =", answer: "69" },
  { prompt: "90 - 1 =", answer: "89" },
  { prompt: "91 - 2 =", answer: "89" },
  { prompt: "92 - 3 =", answer: "89" },
  { prompt: "93 - 4 =", answer: "89" },
  { prompt: "94 - 5 =", answer: "89" },
  { prompt: "95 - 6 =", answer: "89" },
  { prompt: "96 - 7 =", answer: "89" },
  { prompt: "97 - 8 =", answer: "89" },
  { prompt: "98 - 9 =", answer: "89" },
  { prompt: "99 - 10 =", answer: "89" },
  { prompt: "100 - 11 =", answer: "89" },
  { prompt: "101 - 12 =", answer: "89" },
  { prompt: "102 - 13 =", answer: "89" },
  { prompt: "103 - 14 =", answer: "89" },
  { prompt: "104 - 15 =", answer: "89" },

  { prompt: "2 * 2 =", answer: "4" },
  { prompt: "2 * 3 =", answer: "6" },
  { prompt: "2 * 4 =", answer: "8" },
  { prompt: "2 * 5 =", answer: "10" },
  { prompt: "2 * 6 =", answer: "12" },
  { prompt: "3 * 2 =", answer: "6" },
  { prompt: "3 * 3 =", answer: "9" },
  { prompt: "3 * 4 =", answer: "12" },
  { prompt: "3 * 5 =", answer: "15" },
  { prompt: "3 * 6 =", answer: "18" },
  { prompt: "4 * 2 =", answer: "8" },
  { prompt: "4 * 3 =", answer: "12" },
  { prompt: "4 * 4 =", answer: "16" },
  { prompt: "4 * 5 =", answer: "20" },
  { prompt: "4 * 6 =", answer: "24" },
  { prompt: "5 * 2 =", answer: "10" },
  { prompt: "5 * 3 =", answer: "15" },
  { prompt: "5 * 4 =", answer: "20" },
  { prompt: "5 * 5 =", answer: "25" },
  { prompt: "5 * 6 =", answer: "30" },
  { prompt: "6 * 2 =", answer: "12" },
  { prompt: "6 * 3 =", answer: "18" },
  { prompt: "6 * 4 =", answer: "24" },
  { prompt: "6 * 5 =", answer: "30" },
  { prompt: "6 * 6 =", answer: "36" },
  { prompt: "7 * 2 =", answer: "14" },
  { prompt: "7 * 3 =", answer: "21" },
  { prompt: "7 * 4 =", answer: "28" },
  { prompt: "7 * 5 =", answer: "35" },
  { prompt: "7 * 6 =", answer: "42" },
  { prompt: "8 * 2 =", answer: "16" },
  { prompt: "8 * 3 =", answer: "24" },
  { prompt: "8 * 4 =", answer: "32" },
  { prompt: "8 * 5 =", answer: "40" },
  { prompt: "8 * 6 =", answer: "48" },
  { prompt: "9 * 2 =", answer: "18" },
  { prompt: "9 * 3 =", answer: "27" },
  { prompt: "9 * 4 =", answer: "36" },
  { prompt: "9 * 5 =", answer: "45" },
  { prompt: "9 * 6 =", answer: "54" },
  { prompt: "10 * 2 =", answer: "20" },
  { prompt: "10 * 3 =", answer: "30" },
  { prompt: "10 * 4 =", answer: "40" },
  { prompt: "10 * 5 =", answer: "50" },
  { prompt: "10 * 6 =", answer: "60" },
  { prompt: "11 * 2 =", answer: "22" },
  { prompt: "11 * 3 =", answer: "33" },
  { prompt: "11 * 4 =", answer: "44" },
  { prompt: "11 * 5 =", answer: "55" },
  { prompt: "11 * 6 =", answer: "66" },
  { prompt: "12 * 2 =", answer: "24" },
  { prompt: "12 * 3 =", answer: "36" },
  { prompt: "12 * 4 =", answer: "48" },
  { prompt: "12 * 5 =", answer: "60" },
  { prompt: "12 * 6 =", answer: "72" },
  { prompt: "13 * 2 =", answer: "26" },
  { prompt: "13 * 3 =", answer: "39" },
  { prompt: "13 * 4 =", answer: "52" },
  { prompt: "13 * 5 =", answer: "65" },
  { prompt: "13 * 6 =", answer: "78" },
  { prompt: "14 * 2 =", answer: "28" },
  { prompt: "14 * 3 =", answer: "42" },
  { prompt: "14 * 4 =", answer: "56" },
  { prompt: "14 * 5 =", answer: "70" },
  { prompt: "14 * 6 =", answer: "84" },
  { prompt: "15 * 2 =", answer: "30" },
  { prompt: "15 * 3 =", answer: "45" },
  { prompt: "15 * 4 =", answer: "60" },
  { prompt: "15 * 5 =", answer: "75" },
  { prompt: "15 * 6 =", answer: "90" },
  { prompt: "16 * 2 =", answer: "32" },
  { prompt: "16 * 3 =", answer: "48" },
  { prompt: "16 * 4 =", answer: "64" },
  { prompt: "16 * 5 =", answer: "80" },
  { prompt: "16 * 6 =", answer: "96" },

  { prompt: "4 / 2 =", answer: "2" },
  { prompt: "6 / 2 =", answer: "3" },
  { prompt: "8 / 2 =", answer: "4" },
  { prompt: "10 / 2 =", answer: "5" },
  { prompt: "12 / 2 =", answer: "6" },
  { prompt: "6 / 3 =", answer: "2" },
  { prompt: "9 / 3 =", answer: "3" },
  { prompt: "12 / 3 =", answer: "4" },
  { prompt: "15 / 3 =", answer: "5" },
  { prompt: "18 / 3 =", answer: "6" },
  { prompt: "8 / 4 =", answer: "2" },
  { prompt: "12 / 4 =", answer: "3" },
  { prompt: "16 / 4 =", answer: "4" },
  { prompt: "20 / 4 =", answer: "5" },
  { prompt: "24 / 4 =", answer: "6" },
  { prompt: "10 / 5 =", answer: "2" },
  { prompt: "15 / 5 =", answer: "3" },
  { prompt: "20 / 5 =", answer: "4" },
  { prompt: "25 / 5 =", answer: "5" },
  { prompt: "30 / 5 =", answer: "6" },
  { prompt: "12 / 6 =", answer: "2" },
  { prompt: "18 / 6 =", answer: "3" },
  { prompt: "24 / 6 =", answer: "4" },
  { prompt: "30 / 6 =", answer: "5" },
  { prompt: "36 / 6 =", answer: "6" },
  { prompt: "14 / 7 =", answer: "2" },
  { prompt: "21 / 7 =", answer: "3" },
  { prompt: "28 / 7 =", answer: "4" },
  { prompt: "35 / 7 =", answer: "5" },
  { prompt: "42 / 7 =", answer: "6" },
  { prompt: "16 / 8 =", answer: "2" },
  { prompt: "24 / 8 =", answer: "3" },
  { prompt: "32 / 8 =", answer: "4" },
  { prompt: "40 / 8 =", answer: "5" },
  { prompt: "48 / 8 =", answer: "6" },
  { prompt: "18 / 9 =", answer: "2" },
  { prompt: "27 / 9 =", answer: "3" },
  { prompt: "36 / 9 =", answer: "4" },
  { prompt: "45 / 9 =", answer: "5" },
  { prompt: "54 / 9 =", answer: "6" },
  { prompt: "20 / 10 =", answer: "2" },
  { prompt: "30 / 10 =", answer: "3" },
  { prompt: "40 / 10 =", answer: "4" },
  { prompt: "50 / 10 =", answer: "5" },
  { prompt: "60 / 10 =", answer: "6" },
  { prompt: "22 / 11 =", answer: "2" },
  { prompt: "33 / 11 =", answer: "3" },
  { prompt: "44 / 11 =", answer: "4" },
  { prompt: "55 / 11 =", answer: "5" },
  { prompt: "66 / 11 =", answer: "6" },
  { prompt: "24 / 12 =", answer: "2" },
  { prompt: "36 / 12 =", answer: "3" },
  { prompt: "48 / 12 =", answer: "4" },
  { prompt: "60 / 12 =", answer: "5" },
  { prompt: "72 / 12 =", answer: "6" },
  { prompt: "26 / 13 =", answer: "2" },
  { prompt: "39 / 13 =", answer: "3" },
  { prompt: "52 / 13 =", answer: "4" },
  { prompt: "65 / 13 =", answer: "5" },
  { prompt: "78 / 13 =", answer: "6" },
  { prompt: "28 / 14 =", answer: "2" },
  { prompt: "42 / 14 =", answer: "3" },
  { prompt: "56 / 14 =", answer: "4" },
  { prompt: "70 / 14 =", answer: "5" },
  { prompt: "84 / 14 =", answer: "6" },
  { prompt: "30 / 15 =", answer: "2" },
  { prompt: "45 / 15 =", answer: "3" },
  { prompt: "60 / 15 =", answer: "4" },
  { prompt: "75 / 15 =", answer: "5" },
  { prompt: "90 / 15 =", answer: "6" },
  { prompt: "32 / 16 =", answer: "2" },
  { prompt: "48 / 16 =", answer: "3" },
  { prompt: "64 / 16 =", answer: "4" },
  { prompt: "80 / 16 =", answer: "5" },
  { prompt: "96 / 16 =", answer: "6" }
];

export const EMOJI_LIST: GameItem[] = [
  { prompt: "🔥🐶", answer: "hotdog", hint: "A baseball game snack" },
  { prompt: "🍎🥧", answer: "apple pie", hint: "A fruit dessert" },
  { prompt: "❄️👨", answer: "snowman", hint: "Made of freezing water" },
  { prompt: "🌧️🏹", answer: "rainbow", hint: "Colorful arc in the sky" },
  { prompt: "⭐🐟", answer: "starfish", hint: "Has 5 arms in the ocean" },
  { prompt: "🌻", answer: "sunflower", hint: "A tall yellow plant" },
  { prompt: "🕸️👨", answer: "spiderman", hint: "A superhero with webs" },
  { prompt: "🦇👨", answer: "batman", hint: "A dark knight superhero" },
  { prompt: "🥞🍯", answer: "pancakes", hint: "Breakfast food with syrup" },
  { prompt: "🐢🥷", answer: "ninja turtle", hint: "Heroes in a half shell" },
  { prompt: "🍔🍟", answer: "fast food", hint: "Quick meal" },
  { prompt: "🧊☕", answer: "iced coffee", hint: "Cold morning drink" },
  { prompt: "📱🍎", answer: "iphone", hint: "A popular smartphone" },
  { prompt: "🍦🚌", answer: "ice cream truck", hint: "Sells sweet cold treats" },
  { prompt: "🚗⚡", answer: "electric car", hint: "Vehicle that uses batteries" },
  { prompt: "🌲🐻", answer: "forest bear", hint: "Wild animal in woods" },
  { prompt: "🚢🧊", answer: "titanic", hint: "Famous sunken ship" },
  { prompt: "🏠👻", answer: "haunted house", hint: "Scary building" },
  { prompt: "⚽🏟️", answer: "soccer match", hint: "Game played on a pitch" },
  { prompt: "🍿🎥", answer: "movie theater", hint: "Where you watch films" },
  { prompt: "🚀🌕", answer: "moon landing", hint: "Space exploration event" },
  { prompt: "👽🛸", answer: "ufo", hint: "Alien spaceship" },
  { prompt: "🕷️🕸️", answer: "spider web", hint: "Sticky bug trap" },
  { prompt: "🐝🍯", answer: "honey", hint: "Sweet bee product" },
  { prompt: "👨‍🍳🍳", answer: "chef", hint: "Someone who cooks" },
  { prompt: "🐶🦴", answer: "dog bone", hint: "Puppy treat" },
  { prompt: "🐱🐭", answer: "tom and jerry", hint: "Cat and mouse cartoon" },
  { prompt: "🐰🥕", answer: "bugs bunny", hint: "Famous cartoon rabbit" },
  { prompt: "👸🐸", answer: "princess and the frog", hint: "Fairytale story" },
  { prompt: "🍎👸", answer: "snow white", hint: "Eats a poisoned fruit" },
  { prompt: "👠🕕", answer: "cinderella", hint: "Loses a glass slipper" },
  { prompt: "🧜‍♀️🐟", answer: "little mermaid", hint: "Ariel" },
  { prompt: "🦁👑", answer: "lion king", hint: "Hakuna matata" },
  { prompt: "🧸🤠", answer: "toy story", hint: "Woody and Buzz" },
  { prompt: "❄️👸", answer: "frozen", hint: "Let it go" },
  { prompt: "🚗🏁", answer: "cars", hint: "Lightning McQueen" },
  { prompt: "🦸‍♂️🦸‍♀️", answer: "avengers", hint: "Earths mightiest heroes" },
  { prompt: "🧙‍♂️⚡", answer: "harry potter", hint: "The boy who lived" },
  { prompt: "🦖🏞️", answer: "jurassic park", hint: "Dinosaur zoo" },
  { prompt: "🐼🥋", answer: "kung fu panda", hint: "Martial arts bear" },
  { prompt: "👴🎈🏠", answer: "up", hint: "Flying house" },
  { prompt: "🐀👨‍🍳", answer: "ratatouille", hint: "Cooking rat" },
  { prompt: "🐟🔎", answer: "finding nemo", hint: "Lost fish" },
  { prompt: "👹🧅", answer: "shrek", hint: "Ogre with layers" },
  { prompt: "🤠🐎", answer: "cowboy", hint: "Rides horses in the wild west" },
  { prompt: "🏴‍☠️🦜", answer: "pirate", hint: "Sails the seas for treasure" },
  { prompt: "👨‍🚀🌌", answer: "astronaut", hint: "Explores space" },
  { prompt: "👮‍♂️🚓", answer: "police officer", hint: "Catches bad guys" },
  { prompt: "👨‍🚒🚒", answer: "firefighter", hint: "Puts out fires" },
  { prompt: "👨‍⚕️🩺", answer: "doctor", hint: "Helps sick people" },
  { prompt: "👨‍🏫📚", answer: "teacher", hint: "Helps you learn at school" },
  { prompt: "👨‍🌾🚜", answer: "farmer", hint: "Grows food" },
  { prompt: "👨‍🎨🖌️", answer: "artist", hint: "Paints pictures" },
  { prompt: "👨‍🎤🎤", answer: "singer", hint: "Performs music" },
  { prompt: "🕵️‍♂️🔍", answer: "detective", hint: "Solves mysteries" },
  { prompt: "🥷⚔️", answer: "ninja", hint: "Sneaky warrior" },
  { prompt: "🧛‍♂️🦇", answer: "vampire", hint: "Dracula" },
  { prompt: "🧟‍♂️🧠", answer: "zombie", hint: "Eats brains" },
  { prompt: "🧞‍♂️🪔", answer: "genie", hint: "Grants 3 wishes" },
  { prompt: "🧜‍♂️🔱", answer: "merman", hint: "Ocean king" },
  { prompt: "🎅🦌", answer: "santa claus", hint: "Brings presents on christmas" },
  { prompt: "🐰🥚", answer: "easter bunny", hint: "Hides eggs" },
  { prompt: "🧚‍♀️✨", answer: "fairy", hint: "Has wings and magic dust" },
  { prompt: "🧙‍♀️🧹", answer: "witch", hint: "Rides a broom" },
  { prompt: "👸🏰", answer: "princess", hint: "Lives in a castle" },
  { prompt: "🤴👑", answer: "prince", hint: "Son of a king" },
  { prompt: "🐉🔥", answer: "dragon", hint: "Breathes fire" },
  { prompt: "🦄🌈", answer: "unicorn", hint: "Magical horse with a horn" },
  { prompt: "🐶🏠", answer: "doghouse", hint: "Where a dog sleeps" },
  { prompt: "🐱🧶", answer: "cat toy", hint: "Yarn for a kitten" },
  { prompt: "🐭🧀", answer: "mouse trap", hint: "Catches rodents" },
  { prompt: "🐹🎡", answer: "hamster wheel", hint: "Exercise for a small pet" },
  { prompt: "🐰🐇", answer: "bunny rabbit", hint: "Hops around" },
  { prompt: "🦊🐔", answer: "fox and hen", hint: "Predator and prey" },
  { prompt: "🐻🍯", answer: "winnie the pooh", hint: "Bear that loves honey" },
  { prompt: "🐼🎋", answer: "panda bear", hint: "Eats bamboo" },
  { prompt: "🐨🌿", answer: "koala", hint: "Eats eucalyptus leaves" },
  { prompt: "🐯🥩", answer: "tiger", hint: "Big striped cat" },
  { prompt: "🦁🦓", answer: "lion and zebra", hint: "African animals" },
  { prompt: "🐮🥛", answer: "cow milk", hint: "Dairy drink" },
  { prompt: "🐷泥", answer: "pig in mud", hint: "Farm animal" },
  { prompt: "🌽🐶", answer: "corn dog", hint: "A fried fair snack" },
  { prompt: "🍫🥛", answer: "chocolate milk", hint: "A sweet dairy drink" },
  { prompt: "🍓🍰", answer: "strawberry cake", hint: "A fruity dessert" },
  { prompt: "🍌🍞", answer: "banana bread", hint: "A sweet baked loaf" },
  { prompt: "🥜🧈", answer: "peanut butter", hint: "A spread for sandwiches" },
  { prompt: "🍇🧃", answer: "grape juice", hint: "A purple fruit drink" },
  { prompt: "🍋🍰", answer: "lemon cake", hint: "A yellow citrus dessert" },
  { prompt: "🍉🍧", answer: "watermelon ice", hint: "A cold fruity treat" },
  { prompt: "🍕🎉", answer: "pizza party", hint: "A fun meal with friends" },
  { prompt: "🌮🔔", answer: "taco bell", hint: "A fast food restaurant" },

  { prompt: "🐍👢", answer: "snake boots", hint: "Footwear with a reptile style" },
  { prompt: "🐸👑", answer: "frog prince", hint: "A fairytale character" },
  { prompt: "🐺🌕", answer: "werewolf", hint: "Changes under a full moon" },
  { prompt: "🦉📚", answer: "wise owl", hint: "A smart bird" },
  { prompt: "🐝👑", answer: "queen bee", hint: "Leader of the hive" },
  { prompt: "🦋🌸", answer: "butterfly flower", hint: "A garden visitor" },
  { prompt: "🐢💨", answer: "fast turtle", hint: "A silly slow animal going quick" },
  { prompt: "🦀🏖️", answer: "beach crab", hint: "A pinchy animal by the ocean" },
  { prompt: "🐬🌊", answer: "dolphin", hint: "Smart ocean mammal" },
  { prompt: "🦈🌊", answer: "shark", hint: "Big ocean predator" },

  { prompt: "🚒🔥", answer: "fire truck", hint: "Emergency vehicle for fires" },
  { prompt: "🚓👮", answer: "police car", hint: "Vehicle for officers" },
  { prompt: "🚑🏥", answer: "ambulance", hint: "Takes people to the hospital" },
  { prompt: "🚜🌾", answer: "tractor", hint: "Farm vehicle" },
  { prompt: "🚲🏁", answer: "bike race", hint: "Contest on two wheels" },
  { prompt: "🚁🏥", answer: "rescue helicopter", hint: "Flying emergency vehicle" },
  { prompt: "🚂🛤️", answer: "train tracks", hint: "Where trains travel" },
  { prompt: "🚌🏫", answer: "school bus", hint: "Takes kids to class" },
  { prompt: "🚕🏙️", answer: "taxi cab", hint: "Paid city ride" },
  { prompt: "🛳️🏝️", answer: "cruise ship", hint: "Vacation boat" },

  { prompt: "🌎🗺️", answer: "world map", hint: "Shows countries and places" },
  { prompt: "🏔️❄️", answer: "snow mountain", hint: "Cold tall landform" },
  { prompt: "🌋🔥", answer: "volcano", hint: "Mountain that erupts" },
  { prompt: "🏜️🐫", answer: "desert camel", hint: "Animal in sandy places" },
  { prompt: "🌴🏖️", answer: "tropical beach", hint: "Warm sandy vacation spot" },
  { prompt: "🏕️🔥", answer: "campfire", hint: "Fire at a campsite" },
  { prompt: "⛺🌲", answer: "camping", hint: "Sleeping outside" },
  { prompt: "🌉🌃", answer: "city bridge", hint: "Bridge at night" },
  { prompt: "🏰🐉", answer: "dragon castle", hint: "Fantasy place with a monster" },
  { prompt: "🗽🇺🇸", answer: "statue of liberty", hint: "Famous New York landmark" },

  { prompt: "🎂🎈", answer: "birthday party", hint: "Celebration with cake" },
  { prompt: "🎁🎄", answer: "christmas present", hint: "Gift under a tree" },
  { prompt: "🎃👻", answer: "halloween", hint: "Spooky holiday" },
  { prompt: "🦃🍽️", answer: "thanksgiving dinner", hint: "Holiday meal with turkey" },
  { prompt: "💘🌹", answer: "valentine", hint: "Love holiday" },
  { prompt: "🎆🇺🇸", answer: "fourth of july", hint: "Fireworks holiday" },
  { prompt: "🥚🐰", answer: "easter egg", hint: "Holiday egg hunt item" },
  { prompt: "🍀🌈", answer: "st patricks day", hint: "Green lucky holiday" },
  { prompt: "🎓📜", answer: "graduation", hint: "Finishing school celebration" },
  { prompt: "💍👰", answer: "wedding", hint: "Marriage celebration" },

  { prompt: "🎮🕹️", answer: "video game", hint: "Played with a controller" },
  { prompt: "🧩🧠", answer: "brain teaser", hint: "A puzzle for your mind" },
  { prompt: "🎲🏆", answer: "board game", hint: "Tabletop competition" },
  { prompt: "♟️👑", answer: "chess king", hint: "Important game piece" },
  { prompt: "🃏😄", answer: "joker", hint: "Funny card character" },
  { prompt: "🏀🏀", answer: "basketball", hint: "Sport with hoops" },
  { prompt: "⚾🧢", answer: "baseball cap", hint: "Hat worn at games" },
  { prompt: "🏈🏟️", answer: "football game", hint: "Sport played on a field" },
  { prompt: "🎾🎾", answer: "tennis", hint: "Sport with rackets" },
  { prompt: "🏊‍♂️🏅", answer: "swimming medal", hint: "Prize for a pool race" },

  { prompt: "🎤⭐", answer: "pop star", hint: "Famous singer" },
  { prompt: "🎸🔥", answer: "rock star", hint: "Famous guitar musician" },
  { prompt: "🥁🎶", answer: "drum beat", hint: "Rhythm from percussion" },
  { prompt: "🎹🎵", answer: "piano music", hint: "Song from keys" },
  { prompt: "🎧📻", answer: "radio music", hint: "Songs you listen to" },
  { prompt: "🎬⭐", answer: "movie star", hint: "Famous actor" },
  { prompt: "📺🛋️", answer: "tv show", hint: "Watched from the couch" },
  { prompt: "📸😊", answer: "selfie", hint: "Picture of yourself" },
  { prompt: "🎨🖼️", answer: "painting", hint: "Art on a canvas" },
  { prompt: "📚🐛", answer: "bookworm", hint: "Someone who loves reading" },

  { prompt: "🧪🔬", answer: "science lab", hint: "Place for experiments" },
  { prompt: "🧲🧲", answer: "magnet", hint: "Attracts metal" },
  { prompt: "💡🧠", answer: "bright idea", hint: "A smart thought" },
  { prompt: "🔋⚡", answer: "battery power", hint: "Energy from a battery" },
  { prompt: "🧊🥶", answer: "ice cold", hint: "Very chilly" },
  { prompt: "🔥🥵", answer: "hot fire", hint: "Very warm flames" },
  { prompt: "🌪️🏠", answer: "tornado", hint: "Spinning storm" },
  { prompt: "⚡🌧️", answer: "thunderstorm", hint: "Rain with lightning" },
  { prompt: "☀️😎", answer: "sunny day", hint: "Bright weather" },
  { prompt: "🌙😴", answer: "sleepy night", hint: "Time to rest" },

  { prompt: "🧢👕", answer: "baseball shirt", hint: "Clothes for a sporty outfit" },
  { prompt: "👟🏃", answer: "running shoes", hint: "Footwear for jogging" },
  { prompt: "🧤❄️", answer: "winter gloves", hint: "Keep hands warm" },
  { prompt: "🧣☃️", answer: "snow scarf", hint: "Warm neck clothing" },
  { prompt: "👑💎", answer: "royal crown", hint: "Fancy headwear for a ruler" },
  { prompt: "🎒🏫", answer: "school backpack", hint: "Carries books to class" },
  { prompt: "🛏️😴", answer: "bedtime", hint: "Time to sleep" },
  { prompt: "🪥😁", answer: "brush teeth", hint: "Clean your smile" },
  { prompt: "🧼🛁", answer: "bath time", hint: "Time to get clean" },
  { prompt: "🧦🦶", answer: "sock", hint: "Goes on your foot" },

  { prompt: "🏥👶", answer: "baby doctor", hint: "Doctor for little kids" },
  { prompt: "👨‍🍳🍕", answer: "pizza chef", hint: "Person who makes pizza" },
  { prompt: "👩‍🚀🚀", answer: "space astronaut", hint: "Person who flies to space" },
  { prompt: "👨‍🔧🔧", answer: "mechanic", hint: "Fixes machines and cars" },
  { prompt: "👩‍💻💻", answer: "computer programmer", hint: "Writes code" },
  { prompt: "👨‍⚖️⚖️", answer: "judge", hint: "Works in a courtroom" },
  { prompt: "👩‍🔬🧪", answer: "scientist", hint: "Does experiments" },
  { prompt: "👨‍✈️✈️", answer: "pilot", hint: "Flies airplanes" },
  { prompt: "🧑‍🚀🌕", answer: "moon astronaut", hint: "Space explorer on the moon" },
  { prompt: "🧑‍🍳🍰", answer: "baker", hint: "Makes cakes and bread" },
  { prompt: "🔥🍗", answer: "hot wings", hint: "Spicy chicken snack" },
  { prompt: "🍫🍰", answer: "chocolate cake", hint: "A sweet cocoa dessert" },
  { prompt: "🍓🥛", answer: "strawberry milk", hint: "A pink fruity drink" },
  { prompt: "🍎🧃", answer: "apple juice", hint: "A fruit drink" },
  { prompt: "🍊🧃", answer: "orange juice", hint: "A citrus drink" },
  { prompt: "🍋🍵", answer: "lemon tea", hint: "A warm citrus drink" },
  { prompt: "🍌🍨", answer: "banana split", hint: "A fruit ice cream dessert" },
  { prompt: "🍇🍬", answer: "grape candy", hint: "A purple sweet treat" },
  { prompt: "🍉🍬", answer: "watermelon candy", hint: "A fruity sweet treat" },
  { prompt: "🍒🥧", answer: "cherry pie", hint: "A red fruit dessert" },

  { prompt: "🍕🍞", answer: "pizza bread", hint: "Bread with pizza flavor" },
  { prompt: "🧀🍔", answer: "cheese burger", hint: "A burger with cheese" },
  { prompt: "🍟🧀", answer: "cheese fries", hint: "Fries covered in cheese" },
  { prompt: "🥓🍔", answer: "bacon burger", hint: "A burger with bacon" },
  { prompt: "🥚🥪", answer: "egg sandwich", hint: "Breakfast between bread" },
  { prompt: "🐟🥪", answer: "fish sandwich", hint: "Seafood between bread" },
  { prompt: "🍗🥪", answer: "chicken sandwich", hint: "Poultry between bread" },
  { prompt: "🌽🍞", answer: "corn bread", hint: "Bread made with corn" },
  { prompt: "🧄🍞", answer: "garlic bread", hint: "Buttery bread with garlic" },
  { prompt: "🧅💍", answer: "onion rings", hint: "Fried circle snack" },

  { prompt: "🐶🏠", answer: "dog house", hint: "A home for a dog" },
  { prompt: "🐱🐟", answer: "cat fish", hint: "A fish with whiskers" },
  { prompt: "🐭🕳️", answer: "mouse hole", hint: "Tiny animal doorway" },
  { prompt: "🐰🥕", answer: "bunny carrot", hint: "A rabbit snack" },
  { prompt: "🐴🏇", answer: "horse race", hint: "A contest with horses" },
  { prompt: "🐮🔔", answer: "cow bell", hint: "Bell worn by a cow" },
  { prompt: "🐷🏦", answer: "piggy bank", hint: "Holds saved money" },
  { prompt: "🐔🍗", answer: "chicken leg", hint: "A drumstick" },
  { prompt: "🦃🍽️", answer: "turkey dinner", hint: "A holiday meal" },
  { prompt: "🐟🎣", answer: "fish hook", hint: "Used to catch fish" },

  { prompt: "🦈🦷", answer: "shark tooth", hint: "Sharp ocean tooth" },
  { prompt: "🐋🌊", answer: "whale wave", hint: "A big ocean splash" },
  { prompt: "🐬🎵", answer: "dolphin song", hint: "Sounds from a smart sea animal" },
  { prompt: "🦀🍰", answer: "crab cake", hint: "Seafood patty" },
  { prompt: "🐙🦵", answer: "octopus leg", hint: "One of eight arms" },
  { prompt: "🦑🖋️", answer: "squid ink", hint: "Dark ocean animal liquid" },
  { prompt: "🐝🐝", answer: "bee hive", hint: "Home for bees" },
  { prompt: "🐞🌿", answer: "ladybug leaf", hint: "A tiny bug on a plant" },
  { prompt: "🦋🪽", answer: "butterfly wings", hint: "Colorful insect wings" },
  { prompt: "🕷️🕸️", answer: "spider web", hint: "Sticky bug trap" },

  { prompt: "☀️🌅", answer: "sun rise", hint: "Morning sky event" },
  { prompt: "🌙🌃", answer: "moon night", hint: "Dark sky time" },
  { prompt: "⭐💡", answer: "star light", hint: "Light from the sky" },
  { prompt: "☁️🏰", answer: "cloud castle", hint: "A castle in the sky" },
  { prompt: "🌧️☔", answer: "rain umbrella", hint: "Keeps you dry" },
  { prompt: "❄️❄️", answer: "snow flake", hint: "Tiny frozen crystal" },
  { prompt: "🌪️🌧️", answer: "tornado storm", hint: "A dangerous spinning storm" },
  { prompt: "⚡🌩️", answer: "lightning storm", hint: "Storm with bright flashes" },
  { prompt: "🔥🏠", answer: "fire house", hint: "A station for firefighters" },
  { prompt: "💧🌊", answer: "water wave", hint: "Moving water" },

  { prompt: "🏠🔑", answer: "house key", hint: "Opens a home" },
  { prompt: "🚪🔔", answer: "door bell", hint: "Button that rings" },
  { prompt: "🪟🧼", answer: "window cleaner", hint: "Cleans glass" },
  { prompt: "🛏️💤", answer: "bed sleep", hint: "Resting place" },
  { prompt: "🛋️📺", answer: "couch tv", hint: "Living room setup" },
  { prompt: "🛁🫧", answer: "bath bubbles", hint: "Foam in the tub" },
  { prompt: "🚿🧼", answer: "shower soap", hint: "Used to wash" },
  { prompt: "🧺👕", answer: "laundry clothes", hint: "Clothes to wash" },
  { prompt: "🧹🪣", answer: "broom bucket", hint: "Cleaning tools" },
  { prompt: "🕯️💡", answer: "candle light", hint: "Small flame glow" },

  { prompt: "🏫🚌", answer: "school bus", hint: "Takes kids to class" },
  { prompt: "📚📖", answer: "book reading", hint: "Looking at words" },
  { prompt: "✏️📄", answer: "pencil paper", hint: "Writing supplies" },
  { prompt: "🖍️🎨", answer: "crayon art", hint: "Colorful drawing" },
  { prompt: "📏📐", answer: "ruler triangle", hint: "Measuring tools" },
  { prompt: "🧮➕", answer: "abacus math", hint: "Counting tool and numbers" },
  { prompt: "🔬🧪", answer: "science experiment", hint: "Lab test" },
  { prompt: "🧠💡", answer: "brain idea", hint: "A smart thought" },
  { prompt: "🏆🐝", answer: "spelling bee", hint: "A word contest" },
  { prompt: "🎒📚", answer: "backpack books", hint: "School bag contents" },

  { prompt: "🚗💨", answer: "car speed", hint: "Fast vehicle movement" },
  { prompt: "🚕🏙️", answer: "taxi city", hint: "A ride in town" },
  { prompt: "🚙🛣️", answer: "car road", hint: "Vehicle path" },
  { prompt: "🚌🚏", answer: "bus stop", hint: "Where buses pick up riders" },
  { prompt: "🚂🛤️", answer: "train tracks", hint: "Rails for a train" },
  { prompt: "✈️🎫", answer: "plane ticket", hint: "Pass for a flight" },
  { prompt: "🚀🌌", answer: "rocket space", hint: "Launch into the stars" },
  { prompt: "🚲🔔", answer: "bike bell", hint: "Rings on handlebars" },
  { prompt: "🛴💨", answer: "scooter speed", hint: "Fast small ride" },
  { prompt: "⛵🌊", answer: "sail boat", hint: "Boat moved by wind" },

  { prompt: "👑🤴", answer: "king prince", hint: "Royal family members" },
  { prompt: "👑👸", answer: "queen princess", hint: "Royal women" },
  { prompt: "🏰👑", answer: "castle crown", hint: "Royal place and item" },
  { prompt: "🐉🔥", answer: "dragon fire", hint: "Fantasy creature breath" },
  { prompt: "🧙‍♂️🪄", answer: "wizard wand", hint: "Magic tool" },
  { prompt: "🧚✨", answer: "fairy dust", hint: "Tiny magic sparkle" },
  { prompt: "🧞🪔", answer: "genie lamp", hint: "Magic wish holder" },
  { prompt: "👻🏠", answer: "ghost house", hint: "Spooky home" },
  { prompt: "💀🏴‍☠️", answer: "skull pirate", hint: "Scary sailor symbol" },
  { prompt: "🧛🦇", answer: "vampire bat", hint: "Dracula animal" },

  { prompt: "🎮🏆", answer: "game trophy", hint: "Prize for winning" },
  { prompt: "🕹️👾", answer: "arcade alien", hint: "Old game enemy" },
  { prompt: "🎲🎲", answer: "dice game", hint: "Game with cubes" },
  { prompt: "♟️👑", answer: "chess king", hint: "Important board game piece" },
  { prompt: "🧩🧠", answer: "puzzle brain", hint: "A thinking challenge" },
  { prompt: "🎯🏹", answer: "target arrow", hint: "Aim and shoot" },
  { prompt: "🏀🏆", answer: "basketball trophy", hint: "Prize for hoop winners" },
  { prompt: "⚽🥅", answer: "soccer goal", hint: "Score in soccer" },
  { prompt: "⚾🧤", answer: "baseball glove", hint: "Used to catch a ball" },
  { prompt: "🏈🏟️", answer: "football stadium", hint: "Where football is played" }
];

export const OPPOSITES_LIST: GameItem[] = [
  { prompt: "hot", answer: "cold", hint: "Opposite of hot" },
  { prompt: "up", answer: "down", hint: "Opposite of up" },
  { prompt: "fast", answer: "slow", hint: "Opposite of fast" },
  { prompt: "big", answer: "small", hint: "Opposite of big" },
  { prompt: "happy", answer: "sad", hint: "Opposite of happy" },
  { prompt: "day", answer: "night", hint: "Opposite of day" },
  { prompt: "good", answer: "bad", hint: "Opposite of good" },
  { prompt: "inside", answer: "outside", hint: "Opposite of inside" },
  { prompt: "left", answer: "right", hint: "Opposite of left" },
  { prompt: "boy", answer: "girl", hint: "Opposite of boy" },
  { prompt: "start", answer: "stop", hint: "Opposite of start" },
  { prompt: "hard", answer: "soft", hint: "Opposite of hard" },
  { prompt: "high", answer: "low", hint: "Opposite of high" },
  { prompt: "near", answer: "far", hint: "Opposite of near" },
  { prompt: "wet", answer: "dry", hint: "Opposite of wet" },
  { prompt: "empty", answer: "full", hint: "Opposite of empty" },
  { prompt: "young", answer: "old", hint: "Opposite of young" },
  { prompt: "new", answer: "old", hint: "Opposite of new" },
  { prompt: "rich", answer: "poor", hint: "Opposite of rich" },
  { prompt: "thick", answer: "thin", hint: "Opposite of thick" },
  { prompt: "wide", answer: "narrow", hint: "Opposite of wide" },
  { prompt: "heavy", answer: "light", hint: "Opposite of heavy" },
  { prompt: "dark", answer: "light", hint: "Opposite of dark" },
  { prompt: "loud", answer: "quiet", hint: "Opposite of loud" },
  { prompt: "sweet", answer: "sour", hint: "Opposite of sweet" },
  { prompt: "clean", answer: "dirty", hint: "Opposite of clean" },
  { prompt: "smooth", answer: "rough", hint: "Opposite of smooth" },
  { prompt: "sharp", answer: "dull", hint: "Opposite of sharp" },
  { prompt: "early", answer: "late", hint: "Opposite of early" },
  { prompt: "first", answer: "last", hint: "Opposite of first" },
  { prompt: "front", answer: "back", hint: "Opposite of front" },
  { prompt: "top", answer: "bottom", hint: "Opposite of top" },
  { prompt: "open", answer: "closed", hint: "Opposite of open" },
  { prompt: "on", answer: "off", hint: "Opposite of on" },
  { prompt: "true", answer: "false", hint: "Opposite of true" },
  { prompt: "yes", answer: "no", hint: "Opposite of yes" },
  { prompt: "always", answer: "never", hint: "Opposite of always" },
  { prompt: "all", answer: "none", hint: "Opposite of all" },
  { prompt: "many", answer: "few", hint: "Opposite of many" },
  { prompt: "more", answer: "less", hint: "Opposite of more" },
  { prompt: "add", answer: "subtract", hint: "Opposite of add" },
  { prompt: "multiply", answer: "divide", hint: "Opposite of multiply" },
  { prompt: "win", answer: "lose", hint: "Opposite of win" },
  { prompt: "pass", answer: "fail", hint: "Opposite of pass" },
  { prompt: "push", answer: "pull", hint: "Opposite of push" },
  { prompt: "throw", answer: "catch", hint: "Opposite of throw" },
  { prompt: "buy", answer: "sell", hint: "Opposite of buy" },
  { prompt: "give", answer: "take", hint: "Opposite of give" },
  { prompt: "come", answer: "go", hint: "Opposite of come" },
  { prompt: "arrive", answer: "depart", hint: "Opposite of arrive" },
  { prompt: "enter", answer: "exit", hint: "Opposite of enter" },
  { prompt: "rise", answer: "fall", hint: "Opposite of rise" },
  { prompt: "sink", answer: "float", hint: "Opposite of sink" },
  { prompt: "build", answer: "destroy", hint: "Opposite of build" },
  { prompt: "create", answer: "destroy", hint: "Opposite of create" },
  { prompt: "live", answer: "die", hint: "Opposite of live" },
  { prompt: "love", answer: "hate", hint: "Opposite of love" },
  { prompt: "laugh", answer: "cry", hint: "Opposite of laugh" },
  { prompt: "smile", answer: "frown", hint: "Opposite of smile" },
  { prompt: "shout", answer: "whisper", hint: "Opposite of shout" },
  { prompt: "sleep", answer: "wake", hint: "Opposite of sleep" },
  { prompt: "stand", answer: "sit", hint: "Opposite of stand" },
  { prompt: "work", answer: "play", hint: "Opposite of work" },
  { prompt: "study", answer: "play", hint: "Opposite of study" },
  { prompt: "remember", answer: "forget", hint: "Opposite of remember" },
  { prompt: "know", answer: "guess", hint: "Opposite of know" },
  { prompt: "ask", answer: "answer", hint: "Opposite of ask" },
  { prompt: "question", answer: "answer", hint: "Opposite of question" },
  { prompt: "lead", answer: "follow", hint: "Opposite of lead" },
  { prompt: "teach", answer: "learn", hint: "Opposite of teach" },
  { prompt: "borrow", answer: "lend", hint: "Opposite of borrow" },
  { prompt: "save", answer: "spend", hint: "Opposite of save" },
  { prompt: "earn", answer: "spend", hint: "Opposite of earn" },
  { prompt: "find", answer: "lose", hint: "Opposite of find" },
  { prompt: "keep", answer: "give", hint: "Opposite of keep" },
  { prompt: "hide", answer: "seek", hint: "Opposite of hide" },
  { prompt: "attack", answer: "defend", hint: "Opposite of attack" },
  { prompt: "fight", answer: "peace", hint: "Opposite of fight" },
  { prompt: "war", answer: "peace", hint: "Opposite of war" }
];

export const FLIPPER_LIST: GameItem[] = [
  { prompt: "rats", answer: "star", hint: "Just type it backwards!" },
  { prompt: "yks", answer: "sky", hint: "Just type it backwards!" },
  { prompt: "eert", answer: "tree", hint: "Just type it backwards!" },
  { prompt: "rewolf", answer: "flower", hint: "Just type it backwards!" },
  { prompt: "ssarg", answer: "grass", hint: "Just type it backwards!" },
  { prompt: "fael", answer: "leaf", hint: "Just type it backwards!" },
  { prompt: "toor", answer: "root", hint: "Just type it backwards!" },
  { prompt: "dees", answer: "seed", hint: "Just type it backwards!" },
  { prompt: "klim", answer: "milk", hint: "Just type it backwards!" },
  { prompt: "ecir", answer: "rice", hint: "Just type it backwards!" },

  { prompt: "sgge", answer: "eggs", hint: "Just type it backwards!" },
  { prompt: "taem", answer: "meat", hint: "Just type it backwards!" },
  { prompt: "nekcihc", answer: "chicken", hint: "Just type it backwards!" },
  { prompt: "dalas", answer: "salad", hint: "Just type it backwards!" },
  { prompt: "ekac", answer: "cake", hint: "Just type it backwards!" },
  { prompt: "eikooc", answer: "cookie", hint: "Just type it backwards!" },
  { prompt: "maerc", answer: "cream", hint: "Just type it backwards!" },
  { prompt: "ragus", answer: "sugar", hint: "Just type it backwards!" },
  { prompt: "tlas", answer: "salt", hint: "Just type it backwards!" },
  { prompt: "tiucsib", answer: "biscuit", hint: "Just type it backwards!" },

  { prompt: "hcaet", answer: "teach", hint: "Just type it backwards!" },
  { prompt: "nrael", answer: "learn", hint: "Just type it backwards!" },
  { prompt: "kniht", answer: "think", hint: "Just type it backwards!" },
  { prompt: "kaeps", answer: "speak", hint: "Just type it backwards!" },
  { prompt: "netsil", answer: "listen", hint: "Just type it backwards!" },
  { prompt: "sraew", answer: "wears", hint: "Just type it backwards!" },
  { prompt: "naelc", answer: "clean", hint: "Just type it backwards!" },
  { prompt: "ytrid", answer: "dirty", hint: "Just type it backwards!" },
  { prompt: "nepo", answer: "open", hint: "Just type it backwards!" },
  { prompt: "desolc", answer: "closed", hint: "Just type it backwards!" },

  { prompt: "yppah", answer: "happy", hint: "Just type it backwards!" },
  { prompt: "das", answer: "sad", hint: "Just type it backwards!" },
  { prompt: "yrgna", answer: "angry", hint: "Just type it backwards!" },
  { prompt: "deracs", answer: "scared", hint: "Just type it backwards!" },
  { prompt: "evarb", answer: "brave", hint: "Just type it backwards!" },
  { prompt: "duol", answer: "loud", hint: "Just type it backwards!" },
  { prompt: "teiuq", answer: "quiet", hint: "Just type it backwards!" },
  { prompt: "tsaf", answer: "fast", hint: "Just type it backwards!" },
  { prompt: "wols", answer: "slow", hint: "Just type it backwards!" },
  { prompt: "yvaeh", answer: "heavy", hint: "Just type it backwards!" },

  { prompt: "thgil", answer: "light", hint: "Just type it backwards!" },
  { prompt: "dloc", answer: "cold", hint: "Just type it backwards!" },
  { prompt: "toh", answer: "hot", hint: "Just type it backwards!" },
  { prompt: "mraw", answer: "warm", hint: "Just type it backwards!" },
  { prompt: "looc", answer: "cool", hint: "Just type it backwards!" },
  { prompt: "teews", answer: "sweet", hint: "Just type it backwards!" },
  { prompt: "ruos", answer: "sour", hint: "Just type it backwards!" },
  { prompt: "rettib", answer: "bitter", hint: "Just type it backwards!" },
  { prompt: "tfos", answer: "soft", hint: "Just type it backwards!" },
  { prompt: "drah", answer: "hard", hint: "Just type it backwards!" },

  { prompt: "nwolc", answer: "clown", hint: "Just type it backwards!" },
  { prompt: "cigam", answer: "magic", hint: "Just type it backwards!" },
  { prompt: "skcirt", answer: "tricks", hint: "Just type it backwards!" },
  { prompt: "nogard", answer: "dragon", hint: "Just type it backwards!" },
  { prompt: "yriaf", answer: "fairy", hint: "Just type it backwards!" },
  { prompt: "tnaig", answer: "giant", hint: "Just type it backwards!" },
  { prompt: "etarip", answer: "pirate", hint: "Just type it backwards!" },
  { prompt: "erusaert", answer: "treasure", hint: "Just type it backwards!" },
  { prompt: "nworc", answer: "crown", hint: "Just type it backwards!" },
  { prompt: "gnik", answer: "king", hint: "Just type it backwards!" },

  { prompt: "neeuq", answer: "queen", hint: "Just type it backwards!" },
  { prompt: "ecnirp", answer: "prince", hint: "Just type it backwards!" },
  { prompt: "ssecnirp", answer: "princess", hint: "Just type it backwards!" },
  { prompt: "thgink", answer: "knight", hint: "Just type it backwards!" },
  { prompt: "dleihs", answer: "shield", hint: "Just type it backwards!" },
  { prompt: "drows", answer: "sword", hint: "Just type it backwards!" },
  { prompt: "eltsac", answer: "castle", hint: "Just type it backwards!" },
  { prompt: "egalliv", answer: "village", hint: "Just type it backwards!" },
  { prompt: "ytic", answer: "city", hint: "Just type it backwards!" },
  { prompt: "mraf", answer: "farm", hint: "Just type it backwards!" },

  { prompt: "nedrag", answer: "garden", hint: "Just type it backwards!" },
  { prompt: "nrab", answer: "barn", hint: "Just type it backwards!" },
  { prompt: "etag", answer: "gate", hint: "Just type it backwards!" },
  { prompt: "ecnef", answer: "fence", hint: "Just type it backwards!" },
  { prompt: "dleif", answer: "field", hint: "Just type it backwards!" },
  { prompt: "llih", answer: "hill", hint: "Just type it backwards!" },
  { prompt: "niatnuom", answer: "mountain", hint: "Just type it backwards!" },
  { prompt: "revir", answer: "river", hint: "Just type it backwards!" },
  { prompt: "ekal", answer: "lake", hint: "Just type it backwards!" },
  { prompt: "naeco", answer: "ocean", hint: "Just type it backwards!" },

  { prompt: "hcaeb", answer: "beach", hint: "Just type it backwards!" },
  { prompt: "dnas", answer: "sand", hint: "Just type it backwards!" },
  { prompt: "kcor", answer: "rock", hint: "Just type it backwards!" },
  { prompt: "llehs", answer: "shell", hint: "Just type it backwards!" },
  { prompt: "evaw", answer: "wave", hint: "Just type it backwards!" },
  { prompt: "taeh", answer: "heat", hint: "Just type it backwards!" },
  { prompt: "esion", answer: "noise", hint: "Just type it backwards!" },
  { prompt: "cisum", answer: "music", hint: "Just type it backwards!" },
  { prompt: "noitom", answer: "motion", hint: "Just type it backwards!" },
  { prompt: "epahs", answer: "shape", hint: "Just type it backwards!" },

  { prompt: "elcric", answer: "circle", hint: "Just type it backwards!" },
  { prompt: "erauqs", answer: "square", hint: "Just type it backwards!" },
  { prompt: "elgnairt", answer: "triangle", hint: "Just type it backwards!" },
  { prompt: "traeh", answer: "heart", hint: "Just type it backwards!" },
  { prompt: "renroc", answer: "corner", hint: "Just type it backwards!" },
  { prompt: "enil", answer: "line", hint: "Just type it backwards!" },
  { prompt: "tod", answer: "dot", hint: "Just type it backwards!" },
  { prompt: "roloc", answer: "color", hint: "Just type it backwards!" },
  { prompt: "rebmun", answer: "number", hint: "Just type it backwards!" },
  { prompt: "rettel", answer: "letter", hint: "Just type it backwards!" },
  { prompt: "eulb", answer: "blue", hint: "Just type it backwards!" },
  { prompt: "der", answer: "red", hint: "Just type it backwards!" },
  { prompt: "neerg", answer: "green", hint: "Just type it backwards!" },
  { prompt: "wolley", answer: "yellow", hint: "Just type it backwards!" },
  { prompt: "egnaro", answer: "orange", hint: "Just type it backwards!" },
  { prompt: "elprup", answer: "purple", hint: "Just type it backwards!" },
  { prompt: "knip", answer: "pink", hint: "Just type it backwards!" },
  { prompt: "nworb", answer: "brown", hint: "Just type it backwards!" },
  { prompt: "kcalb", answer: "black", hint: "Just type it backwards!" },
  { prompt: "etihw", answer: "white", hint: "Just type it backwards!" },

  { prompt: "taeb", answer: "beat", hint: "Just type it backwards!" },
  { prompt: "pmurd", answer: "drump", hint: "Just type it backwards!" },
  { prompt: "raug", answer: "guar", hint: "Just type it backwards!" },
  { prompt: "ratiug", answer: "guitar", hint: "Just type it backwards!" },
  { prompt: "onaip", answer: "piano", hint: "Just type it backwards!" },
  { prompt: "nroht", answer: "thorn", hint: "Just type it backwards!" },
  { prompt: "lleb", answer: "bell", hint: "Just type it backwards!" },
  { prompt: "gnos", answer: "song", hint: "Just type it backwards!" },
  { prompt: "eton", answer: "note", hint: "Just type it backwards!" },
  { prompt: "eciov", answer: "voice", hint: "Just type it backwards!" },

  { prompt: "etalp", answer: "plate", hint: "Just type it backwards!" },
  { prompt: "krof", answer: "fork", hint: "Just type it backwards!" },
  { prompt: "noops", answer: "spoon", hint: "Just type it backwards!" },
  { prompt: "efink", answer: "knife", hint: "Just type it backwards!" },
  { prompt: "puc", answer: "cup", hint: "Just type it backwards!" },
  { prompt: "ssalg", answer: "glass", hint: "Just type it backwards!" },
  { prompt: "lwob", answer: "bowl", hint: "Just type it backwards!" },
  { prompt: "hsid", answer: "dish", hint: "Just type it backwards!" },
  { prompt: "nevO".toLowerCase(), answer: "oven", hint: "Just type it backwards!" },
  { prompt: "evots", answer: "stove", hint: "Just type it backwards!" },

  { prompt: "kcaj", answer: "jack", hint: "Just type it backwards!" },
  { prompt: "llod", answer: "doll", hint: "Just type it backwards!" },
  { prompt: "yek", answer: "key", hint: "Just type it backwards!" },
  { prompt: "kcol", answer: "lock", hint: "Just type it backwards!" },
  { prompt: "gab", answer: "bag", hint: "Just type it backwards!" },
  { prompt: "xob", answer: "box", hint: "Just type it backwards!" },
  { prompt: "llab", answer: "ball", hint: "Just type it backwards!" },
  { prompt: "emag", answer: "game", hint: "Just type it backwards!" },
  { prompt: "yot", answer: "toy", hint: "Just type it backwards!" },
  { prompt: "kcolc", answer: "clock", hint: "Just type it backwards!" },

  { prompt: "ekoj", answer: "joke", hint: "Just type it backwards!" },
  { prompt: "yrots", answer: "story", hint: "Just type it backwards!" },
  { prompt: "meop", answer: "poem", hint: "Just type it backwards!" },
  { prompt: "drow", answer: "word", hint: "Just type it backwards!" },
  { prompt: "egap", answer: "page", hint: "Just type it backwards!" },
  { prompt: "revoc", answer: "cover", hint: "Just type it backwards!" },
  { prompt: "elbat", answer: "table", hint: "Just type it backwards!" },
  { prompt: "riahc", answer: "chair", hint: "Just type it backwards!" },
  { prompt: "hcuoc", answer: "couch", hint: "Just type it backwards!" },
  { prompt: "teprac", answer: "carpet", hint: "Just type it backwards!" },

  { prompt: "tac", answer: "cat", hint: "Just type it backwards!" },
  { prompt: "god", answer: "dog", hint: "Just type it backwards!" },
  { prompt: "esuom", answer: "mouse", hint: "Just type it backwards!" },
  { prompt: "tibbar", answer: "rabbit", hint: "Just type it backwards!" },
  { prompt: "retsmah", answer: "hamster", hint: "Just type it backwards!" },
  { prompt: "yeknom", answer: "monkey", hint: "Just type it backwards!" },
  { prompt: "arbez", answer: "zebra", hint: "Just type it backwards!" },
  { prompt: "effarig", answer: "giraffe", hint: "Just type it backwards!" },
  { prompt: "adnap", answer: "panda", hint: "Just type it backwards!" },
  { prompt: "alaok", answer: "koala", hint: "Just type it backwards!" },

  { prompt: "reteews", answer: "sweeter", hint: "Just type it backwards!" },
  { prompt: "reddal", answer: "ladder", hint: "Just type it backwards!" },
  { prompt: "wodniw", answer: "window", hint: "Just type it backwards!" },
  { prompt: "rorriM".toLowerCase(), answer: "mirror", hint: "Just type it backwards!" },
  { prompt: "teehs", answer: "sheet", hint: "Just type it backwards!" },
  { prompt: "wollip", answer: "pillow", hint: "Just type it backwards!" },
  { prompt: "teknalb", answer: "blanket", hint: "Just type it backwards!" },
  { prompt: "lesolc", answer: "closel", hint: "Just type it backwards!" },
  { prompt: "teksab", answer: "basket", hint: "Just type it backwards!" },
  { prompt: "lewot", answer: "towel", hint: "Just type it backwards!" },

  { prompt: "ohce", answer: "echo", hint: "Just type it backwards!" },
  { prompt: "knalb", answer: "blank", hint: "Just type it backwards!" },
  { prompt: "tnirp", answer: "print", hint: "Just type it backwards!" },
  { prompt: "egami", answer: "image", hint: "Just type it backwards!" },
  { prompt: "oediv", answer: "video", hint: "Just type it backwards!" },
  { prompt: "retupmoc", answer: "computer", hint: "Just type it backwards!" },
  { prompt: "neercs", answer: "screen", hint: "Just type it backwards!" },
  { prompt: "esuom", answer: "mouse", hint: "Just type it backwards!" },
  { prompt: "drowssap", answer: "password", hint: "Just type it backwards!" },
  { prompt: "liame", answer: "email", hint: "Just type it backwards!" },

  { prompt: "yalpsid", answer: "display", hint: "Just type it backwards!" },
  { prompt: "tniop", answer: "point", hint: "Just type it backwards!" },
  { prompt: "kcilc", answer: "click", hint: "Just type it backwards!" },
  { prompt: "hsup", answer: "push", hint: "Just type it backwards!" },
  { prompt: "llup", answer: "pull", hint: "Just type it backwards!" },
  { prompt: "nrut", answer: "turn", hint: "Just type it backwards!" },
  { prompt: "pots", answer: "stop", hint: "Just type it backwards!" },
  { prompt: "trats", answer: "start", hint: "Just type it backwards!" },
  { prompt: "hsinif", answer: "finish", hint: "Just type it backwards!" },
  { prompt: "niw", answer: "win", hint: "Just type it backwards!" },

  { prompt: "esol", answer: "lose", hint: "Just type it backwards!" },
  { prompt: "erocs", answer: "score", hint: "Just type it backwards!" },
  { prompt: "maet", answer: "team", hint: "Just type it backwards!" },
  { prompt: "hcaoc", answer: "coach", hint: "Just type it backwards!" },
  { prompt: "reyalp", answer: "player", hint: "Just type it backwards!" },
  { prompt: "llabtoof", answer: "football", hint: "Just type it backwards!" },
  { prompt: "llabteksab", answer: "basketball", hint: "Just type it backwards!" },
  { prompt: "llabesab", answer: "baseball", hint: "Just type it backwards!" },
  { prompt: "sinneT".toLowerCase(), answer: "tennis", hint: "Just type it backwards!" },
  { prompt: "reccos", answer: "soccer", hint: "Just type it backwards!" }

];

export const SCRAMBLE_LIST: GameItem[] = [
  { prompt: "tac", answer: "cat", hint: "Meow" },
  { prompt: "gdo", answer: "dog", hint: "Woof" },
  { prompt: "iksd", answer: "kids", hint: "Children" },
  { prompt: "nuf", answer: "fun", hint: "Good times" },
  { prompt: "hoto", answer: "hoot", hint: "Owl sound" },
  { prompt: "iktn", answer: "knit", hint: "Make a sweater" },
  { prompt: "thbae", answer: "bathe", hint: "To wash" },
  { prompt: "mnoo", answer: "moon", hint: "White rock in night sky" },
  { prompt: "kboo", answer: "book", hint: "To read" },
  { prompt: "snu", answer: "sun", hint: "Yellow star in sky" },
  { prompt: "trse", answer: "rest", hint: "To sleep or relax" },
  { prompt: "der", answer: "red", hint: "A color like an apple" },
  { prompt: "eubl", answer: "blue", hint: "A color like the sky" },
  { prompt: "regne", answer: "green", hint: "A color like grass" },
  { prompt: "wloyel", answer: "yellow", hint: "A color like a banana" },
  { prompt: "kalbc", answer: "black", hint: "A very dark color" },
  { prompt: "tihew", answer: "white", hint: "A color like snow" },
  { prompt: "rchi", answer: "rich", hint: "Having lots of money" },
  { prompt: "ropo", answer: "poor", hint: "Having little money" },
  { prompt: "gib", answer: "big", hint: "Large" },
  { prompt: "lmsal", answer: "small", hint: "Little" },

  { prompt: "sliem", answer: "smile", hint: "Happy face" },
  { prompt: "ruyalgh", answer: "laugh", hint: "Sound of joy" },
  { prompt: "yrce", answer: "cry", hint: "Shed tears" },
  { prompt: "pmuj", answer: "jump", hint: "Leap up" },
  { prompt: "nru", answer: "run", hint: "Move fast on feet" },
  { prompt: "klaw", answer: "walk", hint: "Move on foot" },
  { prompt: "imsw", answer: "swim", hint: "Move through water" },
  { prompt: "igsn", answer: "sing", hint: "Use your voice for music" },
  { prompt: "adnce", answer: "dance", hint: "Move to music" },
  { prompt: "dare", answer: "read", hint: "Look at words" },

  { prompt: "etirw", answer: "write", hint: "Put words on paper" },
  { prompt: "wadr", answer: "draw", hint: "Make a picture" },
  { prompt: "yalp", answer: "play", hint: "Have fun with a game" },
  { prompt: "owrk", answer: "work", hint: "Do a job" },
  { prompt: "pleeh", answer: "help", hint: "Assist someone" },
  { prompt: "kooc", answer: "cook", hint: "Make food" },
  { prompt: "tae", answer: "eat", hint: "Have food" },
  { prompt: "nkrid", answer: "drink", hint: "Have a beverage" },
  { prompt: "pelse", answer: "sleep", hint: "Rest at night" },
  { prompt: "maerd", answer: "dream", hint: "Story while sleeping" },

  { prompt: "clodu", answer: "cloud", hint: "White shape in the sky" },
  { prompt: "nira", answer: "rain", hint: "Water from clouds" },
  { prompt: "wons", answer: "snow", hint: "Frozen flakes" },
  { prompt: "dnwi", answer: "wind", hint: "Moving air" },
  { prompt: "marsot", answer: "storm", hint: "Bad weather" },
  { prompt: "rfeif", answer: "fire", hint: "Hot flames" },
  { prompt: "wreta", answer: "water", hint: "Clear liquid to drink" },
  { prompt: "reah", answer: "hear", hint: "Use your ears" },
  { prompt: "sese", answer: "sees", hint: "Looks at something" },
  { prompt: "lsmel", answer: "smell", hint: "Use your nose" },

  { prompt: "teats", answer: "taste", hint: "Use your tongue" },
  { prompt: "chout", answer: "touch", hint: "Feel with your hands" },
  { prompt: "dnha", answer: "hand", hint: "Part with fingers" },
  { prompt: "ootf", answer: "foot", hint: "Part used to walk" },
  { prompt: "deah", answer: "head", hint: "Top part of the body" },
  { prompt: "eyee", answer: "eye", hint: "Used to see" },
  { prompt: "rea", answer: "ear", hint: "Used to hear" },
  { prompt: "seon", answer: "nose", hint: "Used to smell" },
  { prompt: "thuom", answer: "mouth", hint: "Used to eat and speak" },
  { prompt: "iahr", answer: "hair", hint: "Grows on your head" },

  { prompt: "riach", answer: "chair", hint: "You sit on it" },
  { prompt: "elbat", answer: "table", hint: "Furniture with a flat top" },
  { prompt: "edb", answer: "bed", hint: "You sleep on it" },
  { prompt: "rood", answer: "door", hint: "Opens into a room" },
  { prompt: "wdinow", answer: "window", hint: "You look through it" },
  { prompt: "mroo", answer: "room", hint: "Space inside a house" },
  { prompt: "seuoh", answer: "house", hint: "A place to live" },
  { prompt: "orolf", answer: "floor", hint: "You walk on it indoors" },
  { prompt: "lwal", answer: "wall", hint: "Side of a room" },
  { prompt: "mpla", answer: "lamp", hint: "Gives light" },

  { prompt: "paple", answer: "apple", hint: "Red or green fruit" },
  { prompt: "ananab", answer: "banana", hint: "Long yellow fruit" },
  { prompt: "ergnora", answer: "orange", hint: "Citrus fruit" },
  { prompt: "pare", answer: "pear", hint: "Green fruit with a narrow top" },
  { prompt: "egrap", answer: "grape", hint: "Small fruit in bunches" },
  { prompt: "mleon", answer: "melon", hint: "Large sweet fruit" },
  { prompt: "reabd", answer: "bread", hint: "Used for sandwiches" },
  { prompt: "heesec", answer: "cheese", hint: "Made from milk" },
  { prompt: "azzip", answer: "pizza", hint: "Cheesy round food" },
  { prompt: "puos", answer: "soup", hint: "Hot liquid food" },

  { prompt: "lno", answer: "lion", hint: "King of the jungle" },
  { prompt: "rgeit", answer: "tiger", hint: "Striped big cat" },
  { prompt: "raeb", answer: "bear", hint: "Large furry animal" },
  { prompt: "kudc", answer: "duck", hint: "Quacks" },
  { prompt: "dibr", answer: "bird", hint: "Animal with wings" },
  { prompt: "hsif", answer: "fish", hint: "Swims in water" },
  { prompt: "rofg", answer: "frog", hint: "Jumps and says ribbit" },
  { prompt: "keasn", answer: "snake", hint: "Slithers" },
  { prompt: "soreh", answer: "horse", hint: "Animal people ride" },
  { prompt: "woc", answer: "cow", hint: "Gives milk" },

  { prompt: "rac", answer: "car", hint: "Drives on roads" },
  { prompt: "sub", answer: "bus", hint: "Carries many people" },
  { prompt: "nrait", answer: "train", hint: "Runs on tracks" },
  { prompt: "enalp", answer: "plane", hint: "Flies in the sky" },
  { prompt: "taob", answer: "boat", hint: "Floats on water" },
  { prompt: "ekib", answer: "bike", hint: "Has two wheels" },
  { prompt: "daor", answer: "road", hint: "Cars drive on it" },
  { prompt: "egdirb", answer: "bridge", hint: "Goes over water or roads" },
  { prompt: "tihgl", answer: "light", hint: "Helps you see" },
  { prompt: "ngis", answer: "sign", hint: "Shows information" },

  { prompt: "loolhcs", answer: "school", hint: "Place to learn" },
  { prompt: "caether", answer: "teacher", hint: "Person who helps students learn" },
  { prompt: "tnesdut", answer: "student", hint: "Person who learns" },
  { prompt: "epnapr", answer: "paper", hint: "You write on it" },
  { prompt: "elncip", answer: "pencil", hint: "Used to write or draw" },
  { prompt: "lurer", answer: "ruler", hint: "Used to measure" },
  { prompt: "ksed", answer: "desk", hint: "School table" },
  { prompt: "ssalc", answer: "class", hint: "Group of students" },
  { prompt: "ttsre", answer: "test", hint: "Checks what you know" },
  { prompt: "edgar", answer: "grade", hint: "Score or school level" },
  { prompt: "rats", answer: "star", hint: "Bright object in the night sky" },
  { prompt: "yks", answer: "sky", hint: "Above the clouds" },
  { prompt: "eert", answer: "tree", hint: "Tall plant with leaves" },
  { prompt: "rewolf", answer: "flower", hint: "Colorful plant bloom" },
  { prompt: "sargs", answer: "grass", hint: "Green ground cover" },
  { prompt: "eleaf", answer: "leaf", hint: "Part of a plant" },
  { prompt: "toor", answer: "root", hint: "Underground part of a plant" },
  { prompt: "edse", answer: "seed", hint: "A plant can grow from it" },
  { prompt: "likm", answer: "milk", hint: "White drink from cows" },
  { prompt: "ecir", answer: "rice", hint: "Small white grain" },

  { prompt: "ggse", answer: "eggs", hint: "Breakfast food from chickens" },
  { prompt: "taem", answer: "meat", hint: "Protein food" },
  { prompt: "kniecch", answer: "chicken", hint: "Bird often eaten for dinner" },
  { prompt: "dlasas", answer: "salad", hint: "Cold mix of vegetables" },
  { prompt: "keca", answer: "cake", hint: "Sweet birthday dessert" },
  { prompt: "eikcoo", answer: "cookie", hint: "Small sweet baked treat" },
  { prompt: "maerce", answer: "cream", hint: "Thick dairy topping" },
  { prompt: "ragus", answer: "sugar", hint: "Makes food sweet" },
  { prompt: "tlas", answer: "salt", hint: "Common seasoning" },
  { prompt: "ctusiib", answer: "biscuit", hint: "Small baked bread" },

  { prompt: "tcaeh", answer: "teach", hint: "Help someone learn" },
  { prompt: "nrael", answer: "learn", hint: "Gain knowledge" },
  { prompt: "knith", answer: "think", hint: "Use your mind" },
  { prompt: "kaeps", answer: "speak", hint: "Use words out loud" },
  { prompt: "stenil", answer: "listen", hint: "Pay attention with ears" },
  { prompt: "swrea", answer: "wears", hint: "Has clothes on" },
  { prompt: "naelc", answer: "clean", hint: "Not dirty" },
  { prompt: "ydrit", answer: "dirty", hint: "Needs washing" },
  { prompt: "nepo", answer: "open", hint: "Not closed" },
  { prompt: "desolc", answer: "closed", hint: "Not open" },

  { prompt: "yppah", answer: "happy", hint: "Feeling joy" },
  { prompt: "das", answer: "sad", hint: "Feeling unhappy" },
  { prompt: "yrgna", answer: "angry", hint: "Feeling mad" },
  { prompt: "deiracfs", answer: "scared", hint: "Feeling afraid" },
  { prompt: "varbe", answer: "brave", hint: "Not afraid" },
  { prompt: "mudl", answer: "loud", hint: "Not quiet" },
  { prompt: "teiuq", answer: "quiet", hint: "Not noisy" },
  { prompt: "tsaf", answer: "fast", hint: "Quick" },
  { prompt: "wols", answer: "slow", hint: "Not fast" },
  { prompt: "yvaehl", answer: "heavy", hint: "Hard to lift" },

  { prompt: "thgil", answer: "light", hint: "Easy to carry" },
  { prompt: "droc", answer: "cold", hint: "Low temperature" },
  { prompt: "toh", answer: "hot", hint: "High temperature" },
  { prompt: "mraw", answer: "warm", hint: "A little hot" },
  { prompt: "looc", answer: "cool", hint: "A little cold" },
  { prompt: "teewts", answer: "sweet", hint: "Tastes like sugar" },
  { prompt: "ruos", answer: "sour", hint: "Tastes like lemon" },
  { prompt: "retbit", answer: "bitter", hint: "Not sweet, sharp taste" },
  { prompt: "tfos", answer: "soft", hint: "Easy to squish" },
  { prompt: "drah", answer: "hard", hint: "Not soft" },

  { prompt: "woncl", answer: "clown", hint: "Funny circus performer" },
  { prompt: "cigam", answer: "magic", hint: "Tricks that seem impossible" },
  { prompt: "sckirt", answer: "tricks", hint: "Clever actions or jokes" },
  { prompt: "ragdno", answer: "dragon", hint: "Mythical fire-breathing creature" },
  { prompt: "yrfia", answer: "fairy", hint: "Tiny magical creature" },
  { prompt: "tnagi", answer: "giant", hint: "Very large story creature" },
  { prompt: "rpeota", answer: "pirate", hint: "Sailor who searches for treasure" },
  { prompt: "eerruts", answer: "treasure", hint: "Hidden gold or jewels" },
  { prompt: "nworcs", answer: "crown", hint: "Royal headwear" },
  { prompt: "gnik", answer: "king", hint: "Male ruler" },

  { prompt: "neeuq", answer: "queen", hint: "Female ruler" },
  { prompt: "ecnirp", answer: "prince", hint: "Royal son" },
  { prompt: "ssecnirp", answer: "princess", hint: "Royal daughter" },
  { prompt: "thgink", answer: "knight", hint: "Armored warrior" },
  { prompt: "eldsih", answer: "shield", hint: "Used to block attacks" },
  { prompt: "drows", answer: "sword", hint: "Long sharp weapon in stories" },
  { prompt: "elstac", answer: "castle", hint: "Large home for royalty" },
  { prompt: "egavil", answer: "village", hint: "Small town" },
  { prompt: "ytic", answer: "city", hint: "Large town" },
  { prompt: "mraf", answer: "farm", hint: "Place where food is grown" },

  { prompt: "edragh", answer: "garden", hint: "Place to grow flowers or food" },
  { prompt: "rabn", answer: "barn", hint: "Farm building" },
  { prompt: "etga", answer: "gate", hint: "Door in a fence" },
  { prompt: "ecnfe", answer: "fence", hint: "Barrier around a yard" },
  { prompt: "dleif", answer: "field", hint: "Open land" },
  { prompt: "lliih", answer: "hill", hint: "Small mountain" },
  { prompt: "tnuamoin", answer: "mountain", hint: "Very tall landform" },
  { prompt: "ellirv", answer: "river", hint: "Moving water" },
  { prompt: "ekal", answer: "lake", hint: "Large body of still water" },
  { prompt: "naeco", answer: "ocean", hint: "Huge body of salt water" },

  { prompt: "hcaeb", answer: "beach", hint: "Sandy place by water" },
  { prompt: "dnas", answer: "sand", hint: "Tiny grains at the beach" },
  { prompt: "kcor", answer: "rock", hint: "Hard piece of earth" },
  { prompt: "llehs", answer: "shell", hint: "Found on the beach" },
  { prompt: "evaw", answer: "wave", hint: "Moving water shape" },
  { prompt: "taeh", answer: "heat", hint: "Warmth" },
  { prompt: "ecipso", answer: "noise", hint: "Sound, often unwanted" },
  { prompt: "cisum", answer: "music", hint: "Sounds with rhythm or melody" },
  { prompt: "noitos", answer: "motion", hint: "Movement" },
  { prompt: "epahs", answer: "shape", hint: "Form or outline" },

  { prompt: "elcric", answer: "circle", hint: "Round shape" },
  { prompt: "erauqs", answer: "square", hint: "Shape with four equal sides" },
  { prompt: "elgnairt", answer: "triangle", hint: "Shape with three sides" },
  { prompt: "rathe", answer: "heart", hint: "Shape for love" },
  { prompt: "renroc", answer: "corner", hint: "Where two sides meet" },
  { prompt: "enil", answer: "line", hint: "Long thin mark" },
  { prompt: "tod", answer: "dot", hint: "Tiny round mark" },
  { prompt: "roloc", answer: "color", hint: "Red, blue, or green" },
  { prompt: "rebmun", answer: "number", hint: "Used for counting" },
  { prompt: "rettel", answer: "letter", hint: "Part of the alphabet" }
];
